#
# This file contains configuration flags to customize your site
#

# Site details (displayed in the header)
author: Flizz
name: Flizz Blog
title: Flizz Blog
description: Email Campaigns, Email Automation, and more!
keywords: "email marketing, email marketing email, emails for email marketing, email deployment, email marketing marketing, email mktg, email and marketing, a marketing email, free email automation, email blasting services, marketing service, email campaigns, email campaigner, email marketing services, e marketing, service email marketing, email marketing as a service, email advertising services, free service email, email marketing campaign, email blasts, email marketing firms, best email, clients email, e mail how to write"
logo: /images/logo.png

# Company details
company:
  analytics:
    google_id: 
    google_ads_id: 
    microsoft_clarity_id: 
  cta:
    text: "Optimize your email campaigns"
    url: "https://www.flizz.net/"
  socials:
    youtube: "@JelmerJetten"
    instagram: jelmerjetten
    facebook: 
    tiktok: 
    x: Jelmsen
    linkedin: in/jelmer-jetten-79347942
    pinterest: 
    telegram: 
    discord: 
    github: 
    email: 
    phone: 
  icon_size: "24"
  colors:
    main:
      background: "#000"
      foreground: "#fdfdfd"
    body:
      background: "#000"
      foreground: "#fdfdfd"
    accent: "#5ab8c9"
  fonts:
    google:
      - "Roboto:ital,wght@0,100..900;1,100..900"
    heading: "'Roboto'"
    body: "'Roboto'"

# Navigation items
navigation:
  header:
    - title: "Visit Flizz.net"
      url: "https://www.flizz.net/"
  footer:
    - title: "Terms and Conditions"
      url: "/terms-and-conditions"
    - title: "Privacy Policy"
      url: "/privacy-policy"
    - title: "Cookie Policy"
      url: "/cookie-policy"

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://blog.flizz.net

# Paginate after X amount of posts
paginate: 10

#
# NOTHING TO CHANGE BEYOND THIS POINT
#

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
# ONLY NECESSARY ON SUB-PAGE / GITHUB-BASED HOSTING
baseurl: 

# Theme used as a base
theme: jekyll-swiss

# Slug of paginated page
paginate_path: "/page-:num/"

# Permalink slug (DO NOT TOUCH)
permalink: /:title/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Disable Github Metadata plugin
github: [metadata]

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap
  - jekyll-feed # Create an Atom RSS feed
  - jekyll-paginate # Support pagination of posts

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - __init/
  - init_mac.command
  - init_windows.bat